var SQLList = {
    searchSightName: "SELECT SIGHTID FROM SIGHT_INFO WHERE SIGHTNAME LIKE :keyword",
    findSightName: "SELECT SIGHTID FROM SIGHT_INFO WHERE SIGHTNAME = :sightname",
    findSightID: "SELECT * FROM SIGHT_INFO WHERE SIGHTID = :sightid",
    listColumn: "SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SIGHT_INFO' ORDER BY COLUMN_ID",
    viewFav: "SELECT COUNT(*) FROM USER_FAV WHERE SIGHTID = :sightid", 
    updateFav: "UPDATE SIGHT_INFO SET NUMFAV = :numfav WHERE SIGHTID = :sightid",
    viewWish: "SELECT COUNT(*) FROM USER_WISH WHERE SIGHTID = :sightid", 
    updateWish: "UPDATE SIGHT_INFO SET NUMWISH = :numwish WHERE SIGHTID = :sightid",
    viewStep: "SELECT COUNT(*) FROM USER_STEP WHERE SIGHTID = :sightid", 
    updateStep: "UPDATE SIGHT_INFO SET NUMSTEP = :numstep WHERE SIGHTID = :sightid",
    viewGrade: "SELECT AVG(GRD),COUNT(*) FROM SIGHT_GRD WHERE SIGHTID = :sightid", 
    updateGrade: "UPDATE SIGHT_INFO SET AVGGRD = :avggrd, NUMGRD = :numgrd WHERE SIGHTID = :sightid",
    findCmtSightID: "SELECT CMTID,TIMESTAMP FROM CMT_LIST WHERE SIGHTID = :sightid",
    findCmtID: "SELECT USERID,TIMESTAMP,CMT FROM CMT_LIST WHERE CMTID= :cmtid",
    findMediaSightID: "SELECT MEDIAID,TIMESTAMP FROM MEDIA_LIST WHERE SIGHTID = :sightid GROUP BY TIMESTAMP",
    findMediaID: "SELECT USERID,TIMESTAMP,MEDIAURL FROM MEDIA_LIST WHERE MEDIAID= :mediaid"
};

module.exports = SQLList;

